# Copyright 2020 Vectorized, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: build-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.10

    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: update container base
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            apt-get install -y git sudo pkg-config

        - name: install dependencies
          run: |
            ./install-dependencies.sh
            echo 'deb https://runsafesecurity.jfrog.io/artifactory/debian buster main' | sudo tee -a /etc/apt/sources.list.d/alkemist.list
            apt-get -y install gnupg
            wget -qO - https://runsafesecurity.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -
            apt-get update -y
            apt-get install -y clang-11 alkemist-lfr
            source /etc/profile.d/alkemist-lfr.sh

        - name: build & test
          env:
            CC: clang-11
            CXX: clang++-11
          run: ALKEMIST_LICENSE_KEY=43C678-09EE1B-B8AC0A-3E61BF-BAC94B-V3 lfr-helper ./build.sh -DCMAKE_UNITY_BUILD=ON
